### PR TITLE
Update to MapLive v4.1 (from v3.x.x)

### PR DESCRIPTION
**Pull request by jonathanlurie**
[RD-225](https://maptiler.atlassian.net/browse/RD-225)

This PR also adds the UMD bundles to npmignore because UMD are generally intended for CDN.

[RD-225]: https://maptiler.atlassian.net/browse/RD-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jonathanlurie** [comment]
It also contains the latest version of Client lib.

**Comment by petrsloup** [comment]
Looks good, just please upgrade to the just released 4.1.1 (to also get the bug fix): https://github.com/maplibre/maplibre-gl-js/releases/tag/v4.1.1

**Comment by petrsloup** [comment]
https://github.com/maplibre/maplibre-gl-js/releases/tag/v4.1.2 🙂

**Review by petrsloup — APPROVED** [review]

**Comment by jonathanlurie** [comment]
Closing this PR because superseded by https://github.com/maptiler/maptiler-sdk-js/pull/75

**Pull request closed without merging**
