### PR TITLE
fix type declaration with "bundler"  moduleRes

### PR DESCRIPTION
**Pull request by danirdd92**
Hi @jonathanlurie 

following up on our conversation with my last issue regarding type discoverability,
I did some research and found some mistakes we've made regarding the issue.

Vite's default module resolution is set to "bundler" which comes with typescript 5.0, [source](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler).
it is not legacy and should be the way forward.

some other maintainers have encountered this issue, and [solved it](https://github.com/nolimits4web/swiper/pull/6626)

I have attempted the same solution from source and it worked like a charm.
in regard to backwards compatibility, I have, of course, left everything else like it was although it seems to introduce some duplication.

### CODE REVIEW

**Comment by jonathanlurie** [comment]
Hello @danirdd92 , 
thanks for looking into this! I will test this in different bundling conditions (Vite, Rollup, NextJS, etc.)! Thanks for the links as well!

**Comment by danirdd92** [comment]
@jonathanlurie hi, any update on the matter? it could pose a problem especially with ci

**Comment by danirdd92** [comment]
Hi, I'm pinging this again, this PR could really help for CICD when pulling the package.

**Comment by navidevongit2** [comment]
Just came here to create this very same merge request, but I see [danirdd92](https://github.com/danirdd92) already was first here. I use exactly the same code like him and I can confirm this makes Maptiler-SDK conform with TypeScript 5 and module resolution with bundler.

**Review by navidevongit2 — APPROVED** [review]
Everything fine, works with TypeScript 5 and module resolution with bundler.
I came up with the same solution independently of the author, which proves somehow its correctness.

**Comment by jonathanlurie** [comment]
Hey @danirdd92 @navidevongit2 , after some more tests, it looks fine to do bundler. We are currently working on v1.2.0 that should be released within the next week or two and we'll add the bundler setting as part of it.
Thanks for you patience!

**Comment by LoiKos** [comment]
Hey, 

These changes on types are working but you also need to do the same changes on `@maptiler/client` in order to make client re-exported api correctly typed.

**Comment by toniopelo** [comment]
@LoiKos I did the follow-up PR on the `@maptiler/client` package as mentioned above
@jonathanlurie The `client` part should probably be merged and released before this one so the `sdk` can take the fixed client version in its `package.json` to get all the types working at once :)

**Comment by pr0ton** [comment]
It'd be great if this is merged and released soon. The advertised typescript support is unusable on newer node versions because of this.

**Comment by jonathanlurie** [comment]
@toniopelo yes, definitely going to update the Client lib first, thanks!

**Comment by toniopelo** [comment]
I've hit this issue again, this should be merged and released no @jonathanlurie ? Or something is blocking this ?

**Comment by jonathanlurie** [comment]
Hey @toniopelo , no major blocker, but on our side we are preparing the v1.2 release and this involves doing fairly deep code reviews. We plan to merge this very PR the last because we have tested it locally and it's no longer causing issues.  
We are targeting next week for the release, thanks for your patience! (the SDK team is a small team)

**Review by jonathanlurie — APPROVED** [review]

**Pull request merged**
